### ISSUE TITLE
Func methods have some  TypeError

### ISSUE THREAD

**Issue by nwpulei** [Dhruv-Techapps/auto-click-auto-fill#310]
When I use the function function, the browser throws an error。

Func::console.log("Hello");

Uncaught (in promise) TypeError: crypto.randomUUID is not a function
    at Object.sandboxEval (common.js:24:25)
    at Object.start (func.events.js:28:21)
    at we (index.js:66:28)
    at Object.start (action.js:30:11)
    at async Object.start (actions.js:40:18)
    at async Object.start (batch.js:56:16)
    at async t (config.js:26:5)
    at async Object.checkStartType (config.js:96:28)
    at async index.js:15:98

chrome version is 114.0.5735.198  (x86_64)
os macOS BigSur

**Comment by nwpulei** [comment]
Auto Clicker - AutoFill [DEV]
3.4.32

**Comment by dharmesh-hemaram** [comment]
This has been fixed in latest release
